name: advanced_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  get: ^4.6.1
  flutter_screenutil: ^5.0.1+2
  shimmer: ^2.0.0
  cloud_firestore: ^3.1.5
  freezed: ^1.1.0
  build_runner: ^2.1.7
  firebase_storage: ^10.2.4
  lottie: ^1.2.1
  getwidget: ^2.0.4
  syncfusion_flutter_charts: ^19.4.40
  cached_network_image: ^3.2.0
  google_fonts: ^2.2.0
  carousel_slider: ^4.0.0
  material_floating_search_bar: ^0.3.6
  firestore_search: ^0.1.9
  cupertino_progress_bar: ^0.2.0
  syncfusion_flutter_gauges: ^19.4.42
  chip_list: ^2.3.3+8
  chips_choice_null_safety: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
